### PR TITLE
Maybe fix PCSX2 issue with new BIOS mock code

### PR DESCRIPTION
**Pull request by isJuhn**
Juhn Driving

### CODE REVIEW

**Comment by isJuhn** [comment]
@SixelAlexiS90 try this https://github.com/isJuhn/KAMI/suites/13924892758/artifacts/775171860

**Comment by SixelAlexiS90** [comment]
> @SixelAlexiS90 try this https://github.com/isJuhn/KAMI/suites/13924892758/artifacts/775171860

Hi! Thank you for this, sadly I still get the same issue, KAMI doesn't detect Black (SLUS-21376), KAMI status stays on "Unconnected", even if I press the "On/Off" button. 
Any idea?

**Comment by isJuhn** [comment]
Did you enable pine in pcsx2 and change the port to 28012?

**Comment by SixelAlexiS90** [comment]
> Did you enable pine in pcsx2 and change the port to 28012?

@isJuhn No, what is that?
I've looked at the KAMI homepage here on github and it doesn't talk about that.

**Comment by SixelAlexiS90** [comment]
> It does say in the requirements section. Enable PINE/IPC and set the port at the bottom of advanced settings in pcsx2

Ah ok, I thought it was something automatic due to having a more recent version.
It took ages for me to even find that setting since there was no advanced setting in the first place, I had to enable them in the "Tools" tab.
Honestly I would write up mini tutorial on this in the "Running" section since at least on RPCS3 you have more context, on the PCSX2 side you are left there quite confused if you aren't used to this emulator.

Thank you for the heads up tho, now it finally work, sadly the mouse support has a lot of judder, I guess it's a limitation that can't be overcome?
I'm using the 60FPS patch on Black and it's very noticeable, especially if you turn around with the right analog stick before as a test, it's perfectly smooth in comparison.

**Comment by dio-gh** [comment]
Are you on Windows 11 by any chance?

**Comment by SixelAlexiS90** [comment]
> Are you on Windows 11 by any chance?

No I'm on Windows 10, but it's something noticeable on "MouseInjectorDolphinDuck" as well (tested always with Black, was hoping that KAMI was less prone to this issue).

**Comment by dio-gh** [comment]
Could you try changing the `"MouseHandler"` backend from `"Cursor"` to `"RawInput"` in `config.json`? It's right next to the KAMI executable. It's experimental, but I think it may be in a usable state?

**Comment by SixelAlexiS90** [comment]
> Could you try changing the `"MouseHandler"` backend from `"Cursor"` to `"RawInput"` in `config.json`? The file is next to the KAMI executable. It's experimental, but I think it may be in a usable state?

Just tested it and got pretty much the same results.

**Comment by dio-gh** [comment]
I can reproduce the issue, however, it doesn't seem to be caused by this PR. I checked KAMI v0.0.4 with RDR in RPCS3 and the same thing happens. Will need further investigation, but it's beyond the scope of this PR I'd say.

As for the PR, I get the following message when exiting Black with the hook still being on:
image

**Comment by isJuhn** [comment]
judder and that exception is not related to this PR.

**Pull request merged**
